"""add_totp_secret_to_users

Revision ID: 05e0cf2d5eb9
Revises: f71f922998f4
Create Date: 2025-12-20 01:17:52.568192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e0cf2d5eb9'
down_revision: Union[str, Sequence[str], None] = 'f71f922998f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=32), nullable=True, comment='TOTP密钥，用于双因素认证'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
