"""add_external_accounts_table

Revision ID: 08d510aaf02b
Revises: 89eac48bb723
Create Date: 2025-12-29 14:25:29.845833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d510aaf02b'
down_revision: Union[str, Sequence[str], None] = '89eac48bb723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocked_senders_user_id'), table_name='blocked_senders')
    op.alter_column('users', 'auto_clean_trash',
               existing_type=sa.BOOLEAN(),
               comment='是否自动清空垃圾箱（30天）',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'auto_archive_old',
               existing_type=sa.BOOLEAN(),
               comment='是否自动归档旧邮件（1年）',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auto_archive_old',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否自动归档旧邮件（1年）',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'auto_clean_trash',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否自动清空垃圾箱（30天）',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_blocked_senders_user_id'), 'blocked_senders', ['user_id'], unique=False)
    # ### end Alembic commands ###
