"""add_external_accounts_table

Revision ID: 08d510aaf02b
Revises: 89eac48bb723
Create Date: 2025-12-29 14:25:29.845833

说明：此迁移脚本已被修改为条件执行，以处理生产环境和开发环境数据库结构差异的问题。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d510aaf02b'
down_revision: Union[str, Sequence[str], None] = '89eac48bb723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def index_exists(index_name: str, table_name: str) -> bool:
    """检查索引是否存在"""
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_indexes WHERE indexname = :index_name AND tablename = :table_name"
    ), {"index_name": index_name, "table_name": table_name})
    return result.fetchone() is not None


def column_exists(table_name: str, column_name: str) -> bool:
    """检查列是否存在"""
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns WHERE table_name = :table_name AND column_name = :column_name"
    ), {"table_name": table_name, "column_name": column_name})
    return result.fetchone() is not None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 只有当索引存在时才删除
    if index_exists('ix_blocked_senders_user_id', 'blocked_senders'):
        op.drop_index(op.f('ix_blocked_senders_user_id'), table_name='blocked_senders')
    
    # 只有当列存在时才添加注释
    if column_exists('users', 'auto_clean_trash'):
        op.alter_column('users', 'auto_clean_trash',
                   existing_type=sa.BOOLEAN(),
                   comment='是否自动清空垃圾箱（30天）',
                   existing_nullable=True,
                   existing_server_default=sa.text('true'))
    
    if column_exists('users', 'auto_archive_old'):
        op.alter_column('users', 'auto_archive_old',
                   existing_type=sa.BOOLEAN(),
                   comment='是否自动归档旧邮件（1年）',
                   existing_nullable=True,
                   existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('users', 'auto_archive_old'):
        op.alter_column('users', 'auto_archive_old',
                   existing_type=sa.BOOLEAN(),
                   comment=None,
                   existing_comment='是否自动归档旧邮件（1年）',
                   existing_nullable=True,
                   existing_server_default=sa.text('false'))
    if column_exists('users', 'auto_clean_trash'):
        op.alter_column('users', 'auto_clean_trash',
                   existing_type=sa.BOOLEAN(),
                   comment=None,
                   existing_comment='是否自动清空垃圾箱（30天）',
                   existing_nullable=True,
                   existing_server_default=sa.text('true'))
    if not index_exists('ix_blocked_senders_user_id', 'blocked_senders'):
        op.create_index(op.f('ix_blocked_senders_user_id'), 'blocked_senders', ['user_id'], unique=False)
    # ### end Alembic commands ###
