"""Relax unique constraint on message_id and allow nulls

Revision ID: 0904836911b8
Revises: c3118b23305f
Create Date: 2025-11-30 11:04:15.573755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0904836911b8'
down_revision: Union[str, Sequence[str], None] = 'c3118b23305f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'message_id',
               existing_type=sa.VARCHAR(),
               comment='邮件的全局唯一Message-ID（发送后才有）',
               existing_comment='邮件的全局唯一Message-ID',
               existing_nullable=True)
    op.drop_constraint(op.f('emails_message_id_key'), 'emails', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('emails_message_id_key'), 'emails', ['message_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('emails', 'message_id',
               existing_type=sa.VARCHAR(),
               comment='邮件的全局唯一Message-ID',
               existing_comment='邮件的全局唯一Message-ID（发送后才有）',
               existing_nullable=True)
    # ### end Alembic commands ###
