"""add_deleted_at_to_invite_codes

Revision ID: 2bf3850803e9
Revises: 8852d0d0b01c
Create Date: 2025-12-19 15:23:12.065782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf3850803e9'
down_revision: Union[str, Sequence[str], None] = '8852d0d0b01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('invite_codes')]
    if 'deleted_at' not in columns:
        op.add_column('invite_codes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间，null表示未删除'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('invite_codes')]
    if 'deleted_at' in columns:
        op.drop_column('invite_codes', 'deleted_at')
    # ### end Alembic commands ###
