"""add_login_session_fields

Revision ID: 4a3a82a2ec49
Revises: 2bf3850803e9
Create Date: 2025-12-19 15:42:16.190556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3a82a2ec49'
down_revision: Union[str, Sequence[str], None] = '2bf3850803e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('token_hash', sa.String(length=64), nullable=True, comment='Token哈希值，用于识别会话'))
    op.add_column('user_sessions', sa.Column('browser', sa.String(length=100), nullable=True, comment='浏览器名称'))
    op.add_column('user_sessions', sa.Column('os', sa.String(length=100), nullable=True, comment='操作系统'))
    op.add_column('user_sessions', sa.Column('is_active', sa.Boolean(), nullable=True, comment='会话是否有效'))
    op.add_column('user_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='登录时间'))
    op.add_column('user_sessions', sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最后活跃时间'))
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=False)
    op.drop_constraint(op.f('user_sessions_user_id_fkey'), 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('user_sessions_user_id_fkey'), 'user_sessions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_column('user_sessions', 'last_active_at')
    op.drop_column('user_sessions', 'created_at')
    op.drop_column('user_sessions', 'is_active')
    op.drop_column('user_sessions', 'os')
    op.drop_column('user_sessions', 'browser')
    op.drop_column('user_sessions', 'token_hash')
    # ### end Alembic commands ###
