"""add_login_session_fields

Revision ID: 4a3a82a2ec49
Revises: 2bf3850803e9
Create Date: 2025-12-19 15:42:16.190556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3a82a2ec49'
down_revision: Union[str, Sequence[str], None] = '2bf3850803e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('user_sessions')]
    if 'token_hash' not in columns:
        op.add_column('user_sessions', sa.Column('token_hash', sa.String(length=64), nullable=True, comment='Token哈希值，用于识别会话'))
    if 'browser' not in columns:
        op.add_column('user_sessions', sa.Column('browser', sa.String(length=100), nullable=True, comment='浏览器名称'))
    if 'os' not in columns:
        op.add_column('user_sessions', sa.Column('os', sa.String(length=100), nullable=True, comment='操作系统'))
    if 'is_active' not in columns:
        op.add_column('user_sessions', sa.Column('is_active', sa.Boolean(), nullable=True, comment='会话是否有效'))
    if 'created_at' not in columns:
        op.add_column('user_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='登录时间'))
    if 'last_active_at' not in columns:
        op.add_column('user_sessions', sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最后活跃时间'))

    indexes = [index['name'] for index in inspector.get_indexes('user_sessions')]
    if 'ix_user_sessions_token_hash' not in indexes:
        op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=False)

    fkeys = inspector.get_foreign_keys('user_sessions')
    if any(fk['name'] == 'user_sessions_user_id_fkey' for fk in fkeys):
        op.drop_constraint('user_sessions_user_id_fkey', 'user_sessions', type_='foreignkey')
    
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Recreate the original foreign key if it was dropped
    op.drop_constraint('user_sessions_user_id_fkey', 'user_sessions', type_='foreignkey')
    op.create_foreign_key('user_sessions_user_id_fkey', 'user_sessions', 'users', ['user_id'], ['id'])

    indexes = [index['name'] for index in inspector.get_indexes('user_sessions')]
    if 'ix_user_sessions_token_hash' in indexes:
        op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')

    columns = [c['name'] for c in inspector.get_columns('user_sessions')]
    if 'last_active_at' in columns:
        op.drop_column('user_sessions', 'last_active_at')
    if 'created_at' in columns:
        op.drop_column('user_sessions', 'created_at')
    if 'is_active' in columns:
        op.drop_column('user_sessions', 'is_active')
    if 'os' in columns:
        op.drop_column('user_sessions', 'os')
    if 'browser' in columns:
        op.drop_column('user_sessions', 'browser')
    if 'token_hash' in columns:
        op.drop_column('user_sessions', 'token_hash')
    # ### end Alembic commands ###
