"""add_in_reply_to_and_references_to_emails

Revision ID: 547a76a2f458
Revises: 0904836911b8
Create Date: 2025-12-18 02:26:51.684580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547a76a2f458'
down_revision: Union[str, Sequence[str], None] = '0904836911b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('in_reply_to', sa.String(), nullable=True, comment='回复的邮件的Message-ID'))
    op.add_column('emails', sa.Column('references', sa.Text(), nullable=True, comment='邮件引用链（空格分隔的Message-ID列表）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'references')
    op.drop_column('emails', 'in_reply_to')
    # ### end Alembic commands ###
