"""Add comments to all models and implement soft delete for emails

Revision ID: 7b6697b07b10
Revises: cc1dd2a27018
Create Date: 2025-11-30 09:54:45.050921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b6697b07b10'
down_revision: Union[str, Sequence[str], None] = 'cc1dd2a27018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aliases', 'id',
               existing_type=sa.INTEGER(),
               comment='邮箱别名唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('aliases', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('aliases', 'alias_email',
               existing_type=sa.VARCHAR(),
               comment='别名邮箱地址',
               existing_nullable=False)
    op.alter_column('aliases', 'name',
               existing_type=sa.VARCHAR(),
               comment='别名名称/描述',
               existing_nullable=True)
    op.alter_column('aliases', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='别名是否激活',
               existing_nullable=True)
    op.alter_column('api_keys', 'id',
               existing_type=sa.INTEGER(),
               comment='API密钥唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('api_keys', 'key',
               existing_type=sa.VARCHAR(),
               comment='API密钥字符串',
               existing_nullable=False)
    op.alter_column('api_keys', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='密钥拥有的权限 (JSON格式)',
               existing_nullable=True)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后使用时间',
               existing_nullable=True)
    op.alter_column('attachments', 'id',
               existing_type=sa.INTEGER(),
               comment='附件唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('attachments', 'email_id',
               existing_type=sa.INTEGER(),
               comment='所属邮件的ID',
               existing_nullable=False)
    op.alter_column('attachments', 'filename',
               existing_type=sa.VARCHAR(),
               comment='附件原始文件名',
               existing_nullable=True)
    op.alter_column('attachments', 'content_type',
               existing_type=sa.VARCHAR(),
               comment='附件的MIME类型',
               existing_nullable=True)
    op.alter_column('attachments', 'file_path',
               existing_type=sa.VARCHAR(),
               comment='附件在存储系统中的路径',
               existing_nullable=True)
    op.alter_column('attachments', 'attached_email_id',
               existing_type=sa.INTEGER(),
               comment='如果附件本身是一封邮件(eml)，则关联其ID',
               existing_nullable=True)
    op.alter_column('contacts', 'id',
               existing_type=sa.INTEGER(),
               comment='联系人唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('contacts', 'owner_id',
               existing_type=sa.INTEGER(),
               comment='该联系人所属的用户ID',
               existing_nullable=False)
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(),
               comment='联系人姓名',
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(),
               comment='联系人邮箱',
               existing_nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(),
               comment='联系人电话',
               existing_nullable=True)
    op.alter_column('contacts', 'notes',
               existing_type=sa.TEXT(),
               comment='备注信息',
               existing_nullable=True)
    op.alter_column('domains', 'id',
               existing_type=sa.INTEGER(),
               comment='自定义域名唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('domains', 'domain_name',
               existing_type=sa.VARCHAR(),
               comment='域名名称',
               existing_nullable=False)
    op.alter_column('domains', 'owner_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('domains', 'dkim_selector',
               existing_type=sa.VARCHAR(),
               comment='DKIM选择器',
               existing_nullable=True)
    op.alter_column('domains', 'dkim_private_key',
               existing_type=sa.TEXT(),
               comment='DKIM私钥',
               existing_nullable=True)
    op.alter_column('domains', 'dkim_public_key',
               existing_type=sa.TEXT(),
               comment='DKIM公钥',
               existing_nullable=True)
    op.alter_column('domains', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='域名所有权是否已验证',
               existing_nullable=True)
    op.alter_column('domains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='添加时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_tags', 'email_id',
               existing_type=sa.INTEGER(),
               comment='邮件ID',
               existing_nullable=False)
    op.alter_column('email_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               comment='标签ID',
               existing_nullable=False)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('emails')]
    if 'deleted_at' not in columns:
        op.add_column('emails', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间戳，非空表示已移入回收站'))
    if 'is_purged' not in columns:
        op.add_column('emails', sa.Column('is_purged', sa.Boolean(), nullable=True, comment='是否已从回收站彻底清除'))
    op.alter_column('emails', 'id',
               existing_type=sa.INTEGER(),
               comment='邮件唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('emails', 'folder_id',
               existing_type=sa.INTEGER(),
               comment='邮件所在的文件夹ID',
               existing_nullable=False)
    op.alter_column('emails', 'mailbox_address',
               existing_type=sa.VARCHAR(),
               comment='接收该邮件的邮箱地址（用于区分不同别名/域名收到的邮件）',
               existing_nullable=True)
    op.alter_column('emails', 'message_id',
               existing_type=sa.VARCHAR(),
               comment='邮件的全局唯一Message-ID',
               existing_nullable=True)
    op.alter_column('emails', 'thread_id',
               existing_type=sa.VARCHAR(),
               comment='邮件所属线索的ID',
               existing_nullable=True)
    op.alter_column('emails', 'subject',
               existing_type=sa.VARCHAR(),
               comment='邮件主题',
               existing_nullable=True)
    op.alter_column('emails', 'sender',
               existing_type=sa.VARCHAR(),
               comment='发件人地址',
               existing_nullable=True)
    op.alter_column('emails', 'recipients',
               existing_type=sa.TEXT(),
               comment='收件人地址列表 (JSON或逗号分隔)',
               existing_nullable=True)
    op.alter_column('emails', 'body_text',
               existing_type=sa.TEXT(),
               comment='邮件内容的纯文本版本',
               existing_nullable=True)
    op.alter_column('emails', 'body_html',
               existing_type=sa.TEXT(),
               comment='邮件内容的HTML版本',
               existing_nullable=True)
    op.alter_column('emails', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='邮件接收时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('emails', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment='是否已读',
               existing_nullable=True)
    op.alter_column('emails', 'is_starred',
               existing_type=sa.BOOLEAN(),
               comment='是否已加星标',
               existing_nullable=True)
    op.alter_column('emails', 'is_draft',
               existing_type=sa.BOOLEAN(),
               comment='是否为草稿',
               existing_nullable=True)
    op.alter_column('emails', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='邮件发送时间',
               existing_nullable=True)
    op.alter_column('emails', 'scheduled_send_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='计划发送时间',
               existing_nullable=True)
    op.alter_column('emails', 'snoozed_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='邮件被推迟到何时显示',
               existing_nullable=True)
    op.alter_column('emails', 'is_tracked',
               existing_type=sa.BOOLEAN(),
               comment='是否启用邮件追踪',
               existing_nullable=True)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.alter_column('filters', 'id',
               existing_type=sa.INTEGER(),
               comment='过滤器唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('filters', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('filters', 'name',
               existing_type=sa.VARCHAR(),
               comment='过滤器名称',
               existing_nullable=True)
    op.alter_column('filters', 'priority',
               existing_type=sa.INTEGER(),
               comment='执行优先级，数字越小优先级越高',
               existing_nullable=True)
    op.alter_column('filters', 'conditions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='过滤条件 (JSON格式)',
               existing_nullable=True)
    op.alter_column('filters', 'actions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='满足条件时执行的操作 (JSON格式)',
               existing_nullable=True)
    op.alter_column('plans', 'id',
               existing_type=sa.INTEGER(),
               comment='套餐唯一标识符',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('plans_id_seq'::regclass)"))
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(),
               comment="套餐名称 (e.g., 'Free', 'Pro')",
               existing_nullable=False)
    op.alter_column('plans', 'price_monthly',
               existing_type=sa.NUMERIC(),
               comment='月付价格',
               existing_nullable=True)
    op.alter_column('plans', 'price_yearly',
               existing_type=sa.NUMERIC(),
               comment='年付价格',
               existing_nullable=True)
    op.alter_column('plans', 'storage_quota_bytes',
               existing_type=sa.BIGINT(),
               comment='存储空间配额（字节）',
               existing_nullable=True)
    op.alter_column('plans', 'features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='套餐包含的功能列表 (JSON格式)',
               existing_nullable=True)
    op.alter_column('plans', 'max_domains',
               existing_type=sa.INTEGER(),
               comment='允许绑定的最大域名数量',
               existing_nullable=True)
    op.alter_column('plans', 'max_aliases',
               existing_type=sa.INTEGER(),
               comment='允许创建的最大别名数量',
               existing_nullable=True)
    op.alter_column('plans', 'allow_temp_mail',
               existing_type=sa.BOOLEAN(),
               comment='是否允许使用临时邮箱功能',
               existing_nullable=True)
    op.alter_column('redemption_codes', 'id',
               existing_type=sa.INTEGER(),
               comment='兑换码唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('redemption_codes', 'code',
               existing_type=sa.VARCHAR(),
               comment='兑换码字符串',
               existing_nullable=False)
    op.alter_column('redemption_codes', 'plan_id',
               existing_type=sa.INTEGER(),
               comment='关联的套餐ID',
               existing_nullable=False)
    op.alter_column('redemption_codes', 'duration_days',
               existing_type=sa.INTEGER(),
               comment='可兑换的订阅天数',
               existing_nullable=False)
    op.alter_column('redemption_codes', 'status',
               existing_type=sa.VARCHAR(),
               comment="状态 ('unused', 'used', 'expired')",
               existing_nullable=True)
    op.alter_column('redemption_codes', 'created_by_id',
               existing_type=sa.INTEGER(),
               comment='创建该码的管理员ID',
               existing_nullable=True)
    op.alter_column('redemption_codes', 'used_by_id',
               existing_type=sa.INTEGER(),
               comment='使用该码的用户ID',
               existing_nullable=True)
    op.alter_column('redemption_codes', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='使用时间',
               existing_nullable=True)
    op.alter_column('redemption_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('server_logs', 'id',
               existing_type=sa.BIGINT(),
               comment='日志唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('server_logs', 'level',
               existing_type=sa.VARCHAR(),
               comment="日志级别 ('INFO', 'WARN', 'ERROR')",
               existing_nullable=True)
    op.alter_column('server_logs', 'source',
               existing_type=sa.VARCHAR(),
               comment="日志来源 ('smtp', 'imap', 'web', 'system')",
               existing_nullable=True)
    op.alter_column('server_logs', 'message',
               existing_type=sa.TEXT(),
               comment='日志内容',
               existing_nullable=True)
    op.alter_column('server_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('signatures', 'id',
               existing_type=sa.INTEGER(),
               comment='签名唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('signatures', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('signatures', 'name',
               existing_type=sa.VARCHAR(),
               comment='签名名称',
               existing_nullable=True)
    op.alter_column('signatures', 'content_html',
               existing_type=sa.TEXT(),
               comment='签名的HTML内容',
               existing_nullable=True)
    op.alter_column('signatures', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment='是否为默认签名',
               existing_nullable=True)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.INTEGER(),
               comment='订阅记录唯一标识符',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('subscriptions_id_seq'::regclass)"))
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               comment='所订阅套餐的ID',
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               comment="订阅状态 (e.g., 'active', 'canceled', 'past_due')",
               existing_nullable=True)
    op.alter_column('subscriptions', 'current_period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='当前订阅周期的结束时间',
               existing_nullable=True)
    op.alter_column('tags', 'id',
               existing_type=sa.INTEGER(),
               comment='标签唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tags', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               comment='标签名称',
               existing_nullable=True)
    op.alter_column('tags', 'color',
               existing_type=sa.VARCHAR(),
               comment="标签颜色 (e.g., '#RRGGBB')",
               existing_nullable=True)
    op.alter_column('temp_mailboxes', 'id',
               existing_type=sa.INTEGER(),
               comment='临时邮箱唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('temp_mailboxes', 'owner_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('temp_mailboxes', 'email',
               existing_type=sa.VARCHAR(),
               comment='临时邮箱地址',
               existing_nullable=False)
    op.alter_column('temp_mailboxes', 'purpose',
               existing_type=sa.VARCHAR(),
               comment='创建该临时邮箱的用途',
               existing_nullable=True)
    op.alter_column('temp_mailboxes', 'auto_verify_codes',
               existing_type=sa.BOOLEAN(),
               comment='是否自动提取邮件中的验证码',
               existing_nullable=True)
    op.alter_column('temp_mailboxes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活',
               existing_nullable=True)
    op.alter_column('temp_mailboxes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('templates', 'id',
               existing_type=sa.INTEGER(),
               comment='邮件模板唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('templates', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('templates', 'name',
               existing_type=sa.VARCHAR(),
               comment='模板名称',
               existing_nullable=True)
    op.alter_column('templates', 'subject',
               existing_type=sa.VARCHAR(),
               comment='模板主题',
               existing_nullable=True)
    op.alter_column('templates', 'body_html',
               existing_type=sa.TEXT(),
               comment='模板HTML内容',
               existing_nullable=True)
    op.alter_column('tracking_events', 'id',
               existing_type=sa.INTEGER(),
               comment='追踪事件唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tracking_events', 'pixel_id',
               existing_type=sa.UUID(),
               comment='关联的追踪像素ID',
               existing_nullable=False)
    op.alter_column('tracking_events', 'event_type',
               existing_type=sa.VARCHAR(),
               comment="事件类型 (e.g., 'opened', 'clicked')",
               existing_nullable=True)
    op.alter_column('tracking_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='事件发生时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tracking_events', 'ip_address',
               existing_type=sa.VARCHAR(),
               comment='客户端IP地址',
               existing_nullable=True)
    op.alter_column('tracking_events', 'user_agent',
               existing_type=sa.VARCHAR(),
               comment='客户端User Agent',
               existing_nullable=True)
    op.alter_column('tracking_pixels', 'id',
               existing_type=sa.UUID(),
               comment='追踪像素的唯一UUID',
               existing_nullable=False)
    op.alter_column('tracking_pixels', 'email_id',
               existing_type=sa.INTEGER(),
               comment='关联的邮件ID',
               existing_nullable=False)
    op.alter_column('tracking_pixels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'id',
               existing_type=sa.INTEGER(),
               comment='交易记录唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('transactions', 'subscription_id',
               existing_type=sa.INTEGER(),
               comment='关联的订阅ID (如果适用)',
               existing_nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(),
               comment='交易金额',
               existing_nullable=True)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(),
               comment="货币单位 (e.g., 'USD')",
               existing_nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               comment="交易状态 (e.g., 'succeeded', 'failed')",
               existing_nullable=True)
    op.alter_column('transactions', 'payment_gateway_charge_id',
               existing_type=sa.VARCHAR(),
               comment='支付网关返回的交易ID',
               existing_nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='交易创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'id',
               existing_type=sa.INTEGER(),
               comment='用户会话唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('user_sessions', 'device_info',
               existing_type=sa.VARCHAR(),
               comment="设备信息 (e.g., 'Chrome on Windows')",
               existing_nullable=True)
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.VARCHAR(),
               comment='登录IP地址',
               existing_nullable=True)
    op.alter_column('user_sessions', 'location',
               existing_type=sa.VARCHAR(),
               comment='地理位置信息',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'location',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='地理位置信息',
               existing_nullable=True)
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='登录IP地址',
               existing_nullable=True)
    op.alter_column('user_sessions', 'device_info',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="设备信息 (e.g., 'Chrome on Windows')",
               existing_nullable=True)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户会话唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='交易创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'payment_gateway_charge_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='支付网关返回的交易ID',
               existing_nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="交易状态 (e.g., 'succeeded', 'failed')",
               existing_nullable=True)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="货币单位 (e.g., 'USD')",
               existing_nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(),
               comment=None,
               existing_comment='交易金额',
               existing_nullable=True)
    op.alter_column('transactions', 'subscription_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联的订阅ID (如果适用)',
               existing_nullable=True)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='交易记录唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tracking_pixels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tracking_pixels', 'email_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联的邮件ID',
               existing_nullable=False)
    op.alter_column('tracking_pixels', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='追踪像素的唯一UUID',
               existing_nullable=False)
    op.alter_column('tracking_events', 'user_agent',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='客户端User Agent',
               existing_nullable=True)
    op.alter_column('tracking_events', 'ip_address',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='客户端IP地址',
               existing_nullable=True)
    op.alter_column('tracking_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='事件发生时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tracking_events', 'event_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="事件类型 (e.g., 'opened', 'clicked')",
               existing_nullable=True)
    op.alter_column('tracking_events', 'pixel_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联的追踪像素ID',
               existing_nullable=False)
    op.alter_column('tracking_events', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='追踪事件唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('templates', 'body_html',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='模板HTML内容',
               existing_nullable=True)
    op.alter_column('templates', 'subject',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='模板主题',
               existing_nullable=True)
    op.alter_column('templates', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='模板名称',
               existing_nullable=True)
    op.alter_column('templates', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('templates', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='邮件模板唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('temp_mailboxes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('temp_mailboxes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=True)
    op.alter_column('temp_mailboxes', 'auto_verify_codes',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否自动提取邮件中的验证码',
               existing_nullable=True)
    op.alter_column('temp_mailboxes', 'purpose',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='创建该临时邮箱的用途',
               existing_nullable=True)
    op.alter_column('temp_mailboxes', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='临时邮箱地址',
               existing_nullable=False)
    op.alter_column('temp_mailboxes', 'owner_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('temp_mailboxes', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='临时邮箱唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tags', 'color',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="标签颜色 (e.g., '#RRGGBB')",
               existing_nullable=True)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='标签名称',
               existing_nullable=True)
    op.alter_column('tags', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('tags', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='标签唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('subscriptions', 'current_period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='当前订阅周期的结束时间',
               existing_nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="订阅状态 (e.g., 'active', 'canceled', 'past_due')",
               existing_nullable=True)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所订阅套餐的ID',
               existing_nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='订阅记录唯一标识符',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('subscriptions_id_seq'::regclass)"))
    op.alter_column('signatures', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为默认签名',
               existing_nullable=True)
    op.alter_column('signatures', 'content_html',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='签名的HTML内容',
               existing_nullable=True)
    op.alter_column('signatures', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='签名名称',
               existing_nullable=True)
    op.alter_column('signatures', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('signatures', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='签名唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('server_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('server_logs', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='日志内容',
               existing_nullable=True)
    op.alter_column('server_logs', 'source',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="日志来源 ('smtp', 'imap', 'web', 'system')",
               existing_nullable=True)
    op.alter_column('server_logs', 'level',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="日志级别 ('INFO', 'WARN', 'ERROR')",
               existing_nullable=True)
    op.alter_column('server_logs', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='日志唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('redemption_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('redemption_codes', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='使用时间',
               existing_nullable=True)
    op.alter_column('redemption_codes', 'used_by_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='使用该码的用户ID',
               existing_nullable=True)
    op.alter_column('redemption_codes', 'created_by_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='创建该码的管理员ID',
               existing_nullable=True)
    op.alter_column('redemption_codes', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="状态 ('unused', 'used', 'expired')",
               existing_nullable=True)
    op.alter_column('redemption_codes', 'duration_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='可兑换的订阅天数',
               existing_nullable=False)
    op.alter_column('redemption_codes', 'plan_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联的套餐ID',
               existing_nullable=False)
    op.alter_column('redemption_codes', 'code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='兑换码字符串',
               existing_nullable=False)
    op.alter_column('redemption_codes', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='兑换码唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('plans', 'allow_temp_mail',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否允许使用临时邮箱功能',
               existing_nullable=True)
    op.alter_column('plans', 'max_aliases',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='允许创建的最大别名数量',
               existing_nullable=True)
    op.alter_column('plans', 'max_domains',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='允许绑定的最大域名数量',
               existing_nullable=True)
    op.alter_column('plans', 'features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='套餐包含的功能列表 (JSON格式)',
               existing_nullable=True)
    op.alter_column('plans', 'storage_quota_bytes',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='存储空间配额（字节）',
               existing_nullable=True)
    op.alter_column('plans', 'price_yearly',
               existing_type=sa.NUMERIC(),
               comment=None,
               existing_comment='年付价格',
               existing_nullable=True)
    op.alter_column('plans', 'price_monthly',
               existing_type=sa.NUMERIC(),
               comment=None,
               existing_comment='月付价格',
               existing_nullable=True)
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="套餐名称 (e.g., 'Free', 'Pro')",
               existing_nullable=False)
    op.alter_column('plans', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='套餐唯一标识符',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('plans_id_seq'::regclass)"))
    op.alter_column('filters', 'actions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='满足条件时执行的操作 (JSON格式)',
               existing_nullable=True)
    op.alter_column('filters', 'conditions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='过滤条件 (JSON格式)',
               existing_nullable=True)
    op.alter_column('filters', 'priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='执行优先级，数字越小优先级越高',
               existing_nullable=True)
    op.alter_column('filters', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='过滤器名称',
               existing_nullable=True)
    op.alter_column('filters', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('filters', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='过滤器唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.alter_column('emails', 'is_tracked',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用邮件追踪',
               existing_nullable=True)
    op.alter_column('emails', 'snoozed_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='邮件被推迟到何时显示',
               existing_nullable=True)
    op.alter_column('emails', 'scheduled_send_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='计划发送时间',
               existing_nullable=True)
    op.alter_column('emails', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='邮件发送时间',
               existing_nullable=True)
    op.alter_column('emails', 'is_draft',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为草稿',
               existing_nullable=True)
    op.alter_column('emails', 'is_starred',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已加星标',
               existing_nullable=True)
    op.alter_column('emails', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已读',
               existing_nullable=True)
    op.alter_column('emails', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='邮件接收时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('emails', 'body_html',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='邮件内容的HTML版本',
               existing_nullable=True)
    op.alter_column('emails', 'body_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='邮件内容的纯文本版本',
               existing_nullable=True)
    op.alter_column('emails', 'recipients',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='收件人地址列表 (JSON或逗号分隔)',
               existing_nullable=True)
    op.alter_column('emails', 'sender',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='发件人地址',
               existing_nullable=True)
    op.alter_column('emails', 'subject',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='邮件主题',
               existing_nullable=True)
    op.alter_column('emails', 'thread_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='邮件所属线索的ID',
               existing_nullable=True)
    op.alter_column('emails', 'message_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='邮件的全局唯一Message-ID',
               existing_nullable=True)
    op.alter_column('emails', 'mailbox_address',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='接收该邮件的邮箱地址（用于区分不同别名/域名收到的邮件）',
               existing_nullable=True)
    op.alter_column('emails', 'folder_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='邮件所在的文件夹ID',
               existing_nullable=False)
    op.alter_column('emails', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='邮件唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('emails')]
    if 'is_purged' in columns:
        op.drop_column('emails', 'is_purged')
    if 'deleted_at' in columns:
        op.drop_column('emails', 'deleted_at')
    op.alter_column('email_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='标签ID',
               existing_nullable=False)
    op.alter_column('email_tags', 'email_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='邮件ID',
               existing_nullable=False)
    op.alter_column('domains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='添加时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('domains', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='域名所有权是否已验证',
               existing_nullable=True)
    op.alter_column('domains', 'dkim_public_key',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='DKIM公钥',
               existing_nullable=True)
    op.alter_column('domains', 'dkim_private_key',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='DKIM私钥',
               existing_nullable=True)
    op.alter_column('domains', 'dkim_selector',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='DKIM选择器',
               existing_nullable=True)
    op.alter_column('domains', 'owner_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('domains', 'domain_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='域名名称',
               existing_nullable=False)
    op.alter_column('domains', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='自定义域名唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('contacts', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注信息',
               existing_nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='联系人电话',
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='联系人邮箱',
               existing_nullable=True)
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='联系人姓名',
               existing_nullable=True)
    op.alter_column('contacts', 'owner_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='该联系人所属的用户ID',
               existing_nullable=False)
    op.alter_column('contacts', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='联系人唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('attachments', 'attached_email_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='如果附件本身是一封邮件(eml)，则关联其ID',
               existing_nullable=True)
    op.alter_column('attachments', 'file_path',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='附件在存储系统中的路径',
               existing_nullable=True)
    op.alter_column('attachments', 'content_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='附件的MIME类型',
               existing_nullable=True)
    op.alter_column('attachments', 'filename',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='附件原始文件名',
               existing_nullable=True)
    op.alter_column('attachments', 'email_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属邮件的ID',
               existing_nullable=False)
    op.alter_column('attachments', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='附件唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('api_keys', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最后使用时间',
               existing_nullable=True)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='密钥拥有的权限 (JSON格式)',
               existing_nullable=True)
    op.alter_column('api_keys', 'key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='API密钥字符串',
               existing_nullable=False)
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='API密钥唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('aliases', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='别名是否激活',
               existing_nullable=True)
    op.alter_column('aliases', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='别名名称/描述',
               existing_nullable=True)
    op.alter_column('aliases', 'alias_email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='别名邮箱地址',
               existing_nullable=False)
    op.alter_column('aliases', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('aliases', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='邮箱别名唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
