"""add_pool_enabled_to_users

Revision ID: 813ab6b351f3
Revises: d09a5fe04d5e
Create Date: 2025-12-18 06:10:23.391786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '813ab6b351f3'
down_revision: Union[str, Sequence[str], None] = 'd09a5fe04d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pool_enabled', sa.Boolean(), nullable=True, comment='是否允许使用账号池功能'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pool_enabled')
    # ### end Alembic commands ###
