"""add_subscription_history_table

Revision ID: 8852d0d0b01c
Revises: b5a8cce8f397
Create Date: 2025-12-19 15:16:03.101634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8852d0d0b01c'
down_revision: Union[str, Sequence[str], None] = 'b5a8cce8f397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
