"""add_privacy_settings_to_users

Revision ID: 89eac48bb723
Revises: 05e0cf2d5eb9
Create Date: 2025-12-20 12:23:38.139365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89eac48bb723'
down_revision: Union[str, Sequence[str], None] = '05e0cf2d5eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spam_filter_level', sa.String(), nullable=True, comment="垃圾邮件过滤级别 ('standard' 或 'strict')"))
    op.add_column('users', sa.Column('block_external_images', sa.Boolean(), nullable=True, comment='是否阻止外部图片加载'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'block_external_images')
    op.drop_column('users', 'spam_filter_level')
    # ### end Alembic commands ###
