"""add_max_temp_mailboxes_and_is_default_to_plans

Revision ID: 8d9cac0f667e
Revises: e6959dd4548b
Create Date: 2025-12-19 14:19:21.867485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9cac0f667e'
down_revision: Union[str, Sequence[str], None] = 'e6959dd4548b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('max_temp_mailboxes', sa.Integer(), nullable=True, comment='允许创建的最大临时邮箱数量'))
    op.add_column('plans', sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认套餐（新用户自动获得）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'is_default')
    op.drop_column('plans', 'max_temp_mailboxes')
    # ### end Alembic commands ###
