"""add_backup_codes_to_users

Revision ID: 9f203dbee7cc
Revises: 04012a65cc1b
Create Date: 2026-04-27 01:48:09.702079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f203dbee7cc'
down_revision: Union[str, Sequence[str], None] = '04012a65cc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('backup_codes', sa.Text(), nullable=True, comment='2FA备份恢复码（JSON数组，bcrypt哈希）'))
    op.drop_index(op.f('ix_wf_executions_workflow_id'), table_name='workflow_executions')
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.create_index(op.f('ix_wf_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.drop_column('users', 'backup_codes')
    # ### end Alembic commands ###
