"""add_pgp_encryption_fields

Revision ID: b32ebb27ede4
Revises: f138b603f8d7
Create Date: 2026-04-27 22:12:29.759019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32ebb27ede4'
down_revision: Union[str, Sequence[str], None] = 'f138b603f8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('is_encrypted', sa.Boolean(), nullable=True, comment='是否为加密邮件'))
    op.add_column('emails', sa.Column('encryption_type', sa.String(length=20), nullable=True, comment='加密类型 (pgp/smime)'))
    op.add_column('users', sa.Column('pgp_public_key', sa.Text(), nullable=True, comment='PGP公钥（ASCII Armor格式）'))
    op.add_column('users', sa.Column('pgp_key_fingerprint', sa.String(length=64), nullable=True, comment='PGP公钥指纹'))
    op.add_column('users', sa.Column('pgp_key_created_at', sa.DateTime(timezone=True), nullable=True, comment='PGP公钥上传时间'))
    op.create_index(op.f('ix_users_pgp_key_fingerprint'), 'users', ['pgp_key_fingerprint'], unique=False)
    op.drop_index(op.f('ix_wf_executions_workflow_id'), table_name='workflow_executions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wf_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.drop_index(op.f('ix_users_pgp_key_fingerprint'), table_name='users')
    op.drop_column('users', 'pgp_key_created_at')
    op.drop_column('users', 'pgp_key_fingerprint')
    op.drop_column('users', 'pgp_public_key')
    op.drop_column('emails', 'encryption_type')
    op.drop_column('emails', 'is_encrypted')
    # ### end Alembic commands ###
