"""add_invite_code_usages_table

Revision ID: b5a8cce8f397
Revises: 8d9cac0f667e
Create Date: 2025-12-19 15:02:23.782128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a8cce8f397'
down_revision: Union[str, Sequence[str], None] = '8d9cac0f667e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
