"""add_reserved_prefixes_table

Revision ID: b697ad2dca3d
Revises: 4a3a82a2ec49
Create Date: 2025-12-19 16:15:17.214799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b697ad2dca3d'
down_revision: Union[str, Sequence[str], None] = '4a3a82a2ec49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
