"""Add table comments to all models

Revision ID: c3118b23305f
Revises: 7b6697b07b10
Create Date: 2025-11-30 09:58:53.986052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3118b23305f'
down_revision: Union[str, Sequence[str], None] = '7b6697b07b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'aliases',
        '存储用户的邮箱别名',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'api_keys',
        '存储用户生成的用于API访问的密钥',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'attachments',
        '存储邮件附件的信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'contacts',
        '存储用户的联系人信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'domains',
        '存储用户绑定的自定义域名',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'email_tags',
        '邮件与标签的多对多关联表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'emails',
        '存储所有邮件的核心内容和元数据',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'filters',
        '存储用户自定义的邮件过滤规则',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'folders',
        '存储用户自定义和系统的邮件文件夹',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'plans',
        '定义了用户可以订阅的不同服务套餐',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'redemption_codes',
        '存储用于兑换订阅时长的兑换码',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'server_logs',
        '记录服务器的关键运行日志',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'signatures',
        '存储用户的邮件签名',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'subscriptions',
        '记录用户的套餐订阅信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'tags',
        '存储用户自定义的邮件标签',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'temp_mailboxes',
        '存储用户创建的临时邮箱',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'templates',
        '存储用户创建的邮件模板',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'tracking_events',
        '记录邮件追踪事件，如打开、点击链接等',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'tracking_pixels',
        '为启用追踪的邮件生成唯一的追踪像素',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'transactions',
        '记录所有支付和退款交易',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'user_sessions',
        '记录用户的活跃会话，用于安全审计和设备管理',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'users',
        '存储所有用户账户的核心信息',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='存储所有用户账户的核心信息',
        schema=None
    )
    op.drop_table_comment(
        'user_sessions',
        existing_comment='记录用户的活跃会话，用于安全审计和设备管理',
        schema=None
    )
    op.drop_table_comment(
        'transactions',
        existing_comment='记录所有支付和退款交易',
        schema=None
    )
    op.drop_table_comment(
        'tracking_pixels',
        existing_comment='为启用追踪的邮件生成唯一的追踪像素',
        schema=None
    )
    op.drop_table_comment(
        'tracking_events',
        existing_comment='记录邮件追踪事件，如打开、点击链接等',
        schema=None
    )
    op.drop_table_comment(
        'templates',
        existing_comment='存储用户创建的邮件模板',
        schema=None
    )
    op.drop_table_comment(
        'temp_mailboxes',
        existing_comment='存储用户创建的临时邮箱',
        schema=None
    )
    op.drop_table_comment(
        'tags',
        existing_comment='存储用户自定义的邮件标签',
        schema=None
    )
    op.drop_table_comment(
        'subscriptions',
        existing_comment='记录用户的套餐订阅信息',
        schema=None
    )
    op.drop_table_comment(
        'signatures',
        existing_comment='存储用户的邮件签名',
        schema=None
    )
    op.drop_table_comment(
        'server_logs',
        existing_comment='记录服务器的关键运行日志',
        schema=None
    )
    op.drop_table_comment(
        'redemption_codes',
        existing_comment='存储用于兑换订阅时长的兑换码',
        schema=None
    )
    op.drop_table_comment(
        'plans',
        existing_comment='定义了用户可以订阅的不同服务套餐',
        schema=None
    )
    op.drop_table_comment(
        'folders',
        existing_comment='存储用户自定义和系统的邮件文件夹',
        schema=None
    )
    op.drop_table_comment(
        'filters',
        existing_comment='存储用户自定义的邮件过滤规则',
        schema=None
    )
    op.drop_table_comment(
        'emails',
        existing_comment='存储所有邮件的核心内容和元数据',
        schema=None
    )
    op.drop_table_comment(
        'email_tags',
        existing_comment='邮件与标签的多对多关联表',
        schema=None
    )
    op.drop_table_comment(
        'domains',
        existing_comment='存储用户绑定的自定义域名',
        schema=None
    )
    op.drop_table_comment(
        'contacts',
        existing_comment='存储用户的联系人信息',
        schema=None
    )
    op.drop_table_comment(
        'attachments',
        existing_comment='存储邮件附件的信息',
        schema=None
    )
    op.drop_table_comment(
        'api_keys',
        existing_comment='存储用户生成的用于API访问的密钥',
        schema=None
    )
    op.drop_table_comment(
        'aliases',
        existing_comment='存储用户的邮箱别名',
        schema=None
    )
    # ### end Alembic commands ###
