"""Add table comments to all models

Revision ID: c3118b23305f
Revises: 7b6697b07b10
Create Date: 2025-11-30 09:58:53.986052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3118b23305f'
down_revision: Union[str, Sequence[str], None] = '7b6697b07b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    table_comments = {
        'aliases': '存储用户的邮箱别名',
        'api_keys': '存储用户生成的用于API访问的密钥',
        'attachments': '存储邮件附件的信息',
        'contacts': '存储用户的联系人信息',
        'domains': '存储用户绑定的自定义域名',
        'email_tags': '邮件与标签的多对多关联表',
        'emails': '存储所有邮件的核心内容和元数据',
        'filters': '存储用户自定义的邮件过滤规则',
        'folders': '存储用户自定义和系统的邮件文件夹',
        'plans': '定义了用户可以订阅的不同服务套餐',
        'redemption_codes': '存储用于兑换订阅时长的兑换码',
        'server_logs': '记录服务器的关键运行日志',
        'signatures': '存储用户的邮件签名',
        'subscriptions': '记录用户的套餐订阅信息',
        'tags': '存储用户自定义的邮件标签',
        'temp_mailboxes': '存储用户创建的临时邮箱',
        'templates': '存储用户创建的邮件模板',
        'tracking_events': '记录邮件追踪事件，如打开、点击链接等',
        'tracking_pixels': '为启用追踪的邮件生成唯一的追踪像素',
        'transactions': '记录所有支付和退款交易',
        'user_sessions': '记录用户的活跃会话，用于安全审计和设备管理',
        'users': '存储所有用户账户的核心信息',
    }

    tables = inspector.get_table_names()
    for table_name, comment in table_comments.items():
        if table_name in tables:
            existing_comment_obj = inspector.get_table_comment(table_name)
            existing_comment = existing_comment_obj.get('text') if existing_comment_obj else None
            if existing_comment != comment:
                op.create_table_comment(
                    table_name,
                    comment,
                    existing_comment=existing_comment,
                    schema=None
                )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    table_comments = {
        'users': '存储所有用户账户的核心信息',
        'user_sessions': '记录用户的活跃会话，用于安全审计和设备管理',
        'transactions': '记录所有支付和退款交易',
        'tracking_pixels': '为启用追踪的邮件生成唯一的追踪像素',
        'tracking_events': '记录邮件追踪事件，如打开、点击链接等',
        'templates': '存储用户创建的邮件模板',
        'temp_mailboxes': '存储用户创建的临时邮箱',
        'tags': '存储用户自定义的邮件标签',
        'subscriptions': '记录用户的套餐订阅信息',
        'signatures': '存储用户的邮件签名',
        'server_logs': '记录服务器的关键运行日志',
        'redemption_codes': '存储用于兑换订阅时长的兑换码',
        'plans': '定义了用户可以订阅的不同服务套餐',
        'folders': '存储用户自定义和系统的邮件文件夹',
        'filters': '存储用户自定义的邮件过滤规则',
        'emails': '存储所有邮件的核心内容和元数据',
        'email_tags': '邮件与标签的多对多关联表',
        'domains': '存储用户绑定的自定义域名',
        'contacts': '存储用户的联系人信息',
        'attachments': '存储邮件附件的信息',
        'api_keys': '存储用户生成的用于API访问的密钥',
        'aliases': '存储用户的邮箱别名',
    }

    tables = inspector.get_table_names()
    for table_name, comment in reversed(list(table_comments.items())):
        if table_name in tables:
            existing_comment_obj = inspector.get_table_comment(table_name)
            existing_comment = existing_comment_obj.get('text') if existing_comment_obj else None
            if existing_comment == comment:
                op.drop_table_comment(
                    table_name,
                    existing_comment=comment,
                    schema=None
                )
    # ### end Alembic commands ###
