"""Add comments to all tables and columns

Revision ID: cc1dd2a27018
Revises: 
Create Date: 2025-11-30 09:41:14.266047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc1dd2a27018'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folders', 'id',
               existing_type=sa.INTEGER(),
               comment='文件夹唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('folders', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('folders', 'name',
               existing_type=sa.VARCHAR(),
               comment='文件夹显示名称',
               existing_nullable=False)
    op.alter_column('folders', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='父文件夹ID，用于支持文件夹嵌套',
               existing_nullable=True)
    op.alter_column('folders', 'role',
               existing_type=sa.VARCHAR(),
               comment="文件夹角色 ('inbox', 'sent', 'drafts', 'trash', 'spam', 'archive' 等系统角色, 或 'user' 自定义文件夹)",
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='用户唯一标识符',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='用户主邮箱地址，用于登录',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               comment='用户手机号，可选，也可用于登录或恢复',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               comment='哈希处理后的用户密码',
               existing_nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               comment='用户显示名称',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               comment='用户头像图片的URL',
               existing_nullable=True)
    op.alter_column('users', 'theme',
               existing_type=sa.VARCHAR(),
               comment="用户界面主题 (e.g., 'light', 'dark', 'system')",
               existing_nullable=True)
    op.alter_column('users', 'recovery_email',
               existing_type=sa.VARCHAR(),
               comment='备用恢复邮箱',
               existing_nullable=True)
    op.alter_column('users', 'two_factor_enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用双因素认证',
               existing_nullable=True)
    op.alter_column('users', 'storage_used_bytes',
               existing_type=sa.BIGINT(),
               comment='已使用的存储空间（字节）',
               existing_nullable=True)
    op.alter_column('users', 'auto_reply_enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用自动回复',
               existing_nullable=True)
    op.alter_column('users', 'auto_reply_start_date',
               existing_type=sa.DATE(),
               comment='自动回复开始日期',
               existing_nullable=True)
    op.alter_column('users', 'auto_reply_end_date',
               existing_type=sa.DATE(),
               comment='自动回复结束日期',
               existing_nullable=True)
    op.alter_column('users', 'auto_reply_message',
               existing_type=sa.TEXT(),
               comment='自动回复的邮件内容',
               existing_nullable=True)
    op.alter_column('users', 'enable_desktop_notifications',
               existing_type=sa.BOOLEAN(),
               comment='是否启用桌面通知',
               existing_nullable=True)
    op.alter_column('users', 'enable_sound_notifications',
               existing_type=sa.BOOLEAN(),
               comment='是否启用声音通知',
               existing_nullable=True)
    op.alter_column('users', 'enable_pool_notifications',
               existing_type=sa.BOOLEAN(),
               comment='是否启用邮件池通知',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               comment="用户角色 ('admin' 或 'user')",
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='用户账户创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='用户账户创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="用户角色 ('admin' 或 'user')",
               existing_nullable=True)
    op.alter_column('users', 'enable_pool_notifications',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用邮件池通知',
               existing_nullable=True)
    op.alter_column('users', 'enable_sound_notifications',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用声音通知',
               existing_nullable=True)
    op.alter_column('users', 'enable_desktop_notifications',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用桌面通知',
               existing_nullable=True)
    op.alter_column('users', 'auto_reply_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='自动回复的邮件内容',
               existing_nullable=True)
    op.alter_column('users', 'auto_reply_end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='自动回复结束日期',
               existing_nullable=True)
    op.alter_column('users', 'auto_reply_start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='自动回复开始日期',
               existing_nullable=True)
    op.alter_column('users', 'auto_reply_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用自动回复',
               existing_nullable=True)
    op.alter_column('users', 'storage_used_bytes',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='已使用的存储空间（字节）',
               existing_nullable=True)
    op.alter_column('users', 'two_factor_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用双因素认证',
               existing_nullable=True)
    op.alter_column('users', 'recovery_email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='备用恢复邮箱',
               existing_nullable=True)
    op.alter_column('users', 'theme',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="用户界面主题 (e.g., 'light', 'dark', 'system')",
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='用户头像图片的URL',
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='用户显示名称',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='哈希处理后的用户密码',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='用户手机号，可选，也可用于登录或恢复',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='用户主邮箱地址，用于登录',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户唯一标识符',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('folders', 'role',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="文件夹角色 ('inbox', 'sent', 'drafts', 'trash', 'spam', 'archive' 等系统角色, 或 'user' 自定义文件夹)",
               existing_nullable=True)
    op.alter_column('folders', 'parent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='父文件夹ID，用于支持文件夹嵌套',
               existing_nullable=True)
    op.alter_column('folders', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='文件夹显示名称',
               existing_nullable=False)
    op.alter_column('folders', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户的ID',
               existing_nullable=False)
    op.alter_column('folders', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='文件夹唯一标识符',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
