"""add_invite_code_table_and_expires_at_to_redemption_code

Revision ID: d09a5fe04d5e
Revises: fc0e721cb44b
Create Date: 2025-12-18 05:35:12.362662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09a5fe04d5e'
down_revision: Union[str, Sequence[str], None] = 'fc0e721cb44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('redemption_codes')]
    if 'expires_at' not in columns:
        op.add_column('redemption_codes', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间，null表示永不过期'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('redemption_codes')]
    if 'expires_at' in columns:
        op.drop_column('redemption_codes', 'expires_at')
    # ### end Alembic commands ###
