"""add_user_id_size_created_at_to_attachments

Revision ID: e6959dd4548b
Revises: 813ab6b351f3
Create Date: 2025-12-18 14:53:11.122187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6959dd4548b'
down_revision: Union[str, Sequence[str], None] = '813ab6b351f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # attachments table
    attachment_columns = [c['name'] for c in inspector.get_columns('attachments')]
    if 'user_id' not in attachment_columns:
        op.add_column('attachments', sa.Column('user_id', sa.Integer(), nullable=False, comment='上传用户ID'))
    if 'size' not in attachment_columns:
        op.add_column('attachments', sa.Column('size', sa.Integer(), nullable=True, comment='文件大小(字节)'))
    if 'created_at' not in attachment_columns:
        op.add_column('attachments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='上传时间'))

    op.alter_column('attachments', 'email_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='所属邮件的ID')
    
    fkeys = inspector.get_foreign_keys('attachments')
    if not any(fk['constrained_columns'] == ['user_id'] for fk in fkeys):
        op.create_foreign_key('attachments_user_id_fkey', 'attachments', 'users', ['user_id'], ['id'])

    # pool_activity_logs table
    op.alter_column('pool_activity_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型: create, delete',
               existing_nullable=False)
    op.alter_column('pool_activity_logs', 'mailbox_email',
               existing_type=sa.VARCHAR(length=255),
               comment='邮箱地址',
               existing_nullable=False)
    op.alter_column('pool_activity_logs', 'details',
               existing_type=sa.TEXT(),
               comment='详细信息',
               existing_nullable=True)

    indexes = [index['name'] for index in inspector.get_indexes('pool_activity_logs')]
    if 'ix_pool_activity_logs_user_id' in indexes:
        op.drop_index(op.f('ix_pool_activity_logs_user_id'), table_name='pool_activity_logs')

    existing_comment_obj = inspector.get_table_comment('pool_activity_logs')
    existing_comment = existing_comment_obj.get('text') if existing_comment_obj else None
    if existing_comment != '账号池操作日志':
        op.create_table_comment(
            'pool_activity_logs',
            '账号池操作日志',
            existing_comment=existing_comment,
            schema=None
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # pool_activity_logs table
    existing_comment_obj = inspector.get_table_comment('pool_activity_logs')
    if existing_comment_obj and existing_comment_obj.get('text') == '账号池操作日志':
        op.drop_table_comment(
            'pool_activity_logs',
            existing_comment='账号池操作日志',
            schema=None
        )

    indexes = [index['name'] for index in inspector.get_indexes('pool_activity_logs')]
    if 'ix_pool_activity_logs_user_id' not in indexes:
        op.create_index(op.f('ix_pool_activity_logs_user_id'), 'pool_activity_logs', ['user_id'], unique=False)

    op.alter_column('pool_activity_logs', 'details',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='详细信息',
               existing_nullable=True)
    op.alter_column('pool_activity_logs', 'mailbox_email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='邮箱地址',
               existing_nullable=False)
    op.alter_column('pool_activity_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='操作类型: create, delete',
               existing_nullable=False)

    # attachments table
    fkeys = inspector.get_foreign_keys('attachments')
    if any(fk['name'] == 'attachments_user_id_fkey' for fk in fkeys):
        op.drop_constraint('attachments_user_id_fkey', 'attachments', type_='foreignkey')

    op.alter_column('attachments', 'email_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='所属邮件的ID')

    attachment_columns = [c['name'] for c in inspector.get_columns('attachments')]
    if 'created_at' in attachment_columns:
        op.drop_column('attachments', 'created_at')
    if 'size' in attachment_columns:
        op.drop_column('attachments', 'size')
    if 'user_id' in attachment_columns:
        op.drop_column('attachments', 'user_id')
    # ### end Alembic commands ###
