"""add_user_id_size_created_at_to_attachments

Revision ID: e6959dd4548b
Revises: 813ab6b351f3
Create Date: 2025-12-18 14:53:11.122187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6959dd4548b'
down_revision: Union[str, Sequence[str], None] = '813ab6b351f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('user_id', sa.Integer(), nullable=False, comment='上传用户ID'))
    op.add_column('attachments', sa.Column('size', sa.Integer(), nullable=True, comment='文件大小(字节)'))
    op.add_column('attachments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='上传时间'))
    op.alter_column('attachments', 'email_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='所属邮件的ID')
    op.create_foreign_key(None, 'attachments', 'users', ['user_id'], ['id'])
    op.alter_column('pool_activity_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型: create, delete',
               existing_nullable=False)
    op.alter_column('pool_activity_logs', 'mailbox_email',
               existing_type=sa.VARCHAR(length=255),
               comment='邮箱地址',
               existing_nullable=False)
    op.alter_column('pool_activity_logs', 'details',
               existing_type=sa.TEXT(),
               comment='详细信息',
               existing_nullable=True)
    op.drop_index(op.f('ix_pool_activity_logs_user_id'), table_name='pool_activity_logs')
    op.create_table_comment(
        'pool_activity_logs',
        '账号池操作日志',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'pool_activity_logs',
        existing_comment='账号池操作日志',
        schema=None
    )
    op.create_index(op.f('ix_pool_activity_logs_user_id'), 'pool_activity_logs', ['user_id'], unique=False)
    op.alter_column('pool_activity_logs', 'details',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='详细信息',
               existing_nullable=True)
    op.alter_column('pool_activity_logs', 'mailbox_email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='邮箱地址',
               existing_nullable=False)
    op.alter_column('pool_activity_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='操作类型: create, delete',
               existing_nullable=False)
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.alter_column('attachments', 'email_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='所属邮件的ID')
    op.drop_column('attachments', 'created_at')
    op.drop_column('attachments', 'size')
    op.drop_column('attachments', 'user_id')
    # ### end Alembic commands ###
