"""add_calendar_events_table

Revision ID: f138b603f8d7
Revises: 82debdab9597
Create Date: 2026-04-27 22:05:55.122580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f138b603f8d7'
down_revision: Union[str, Sequence[str], None] = '82debdab9597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='事件标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='事件描述'),
    sa.Column('location', sa.String(length=500), nullable=True, comment='地点'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='结束时间'),
    sa.Column('all_day', sa.Boolean(), nullable=True, comment='是否全天事件'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='颜色标记'),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True, comment='提前提醒分钟数'),
    sa.Column('source_email_id', sa.Integer(), nullable=True, comment='关联的邮件ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['source_email_id'], ['emails.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='日历事件'
    )
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_time'), 'calendar_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.alter_column('drive_files', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='父文件夹ID',
               existing_nullable=True)
    op.alter_column('drive_files', 'is_folder',
               existing_type=sa.BOOLEAN(),
               comment='是否为文件夹',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('drive_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_wf_executions_workflow_id'), table_name='workflow_executions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wf_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.alter_column('drive_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('drive_files', 'is_folder',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为文件夹',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('drive_files', 'parent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='父文件夹ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_time'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
