"""add delivery_status and delivery_error to emails

Revision ID: fc0e721cb44b
Revises: 547a76a2f458
Create Date: 2025-12-18 03:45:21.399400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0e721cb44b'
down_revision: Union[str, Sequence[str], None] = '547a76a2f458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('emails')]
    if 'delivery_status' not in columns:
        op.add_column('emails', sa.Column('delivery_status', sa.String(), nullable=True, comment='投递状态: pending/sending/sent/delivered/failed'))
    if 'delivery_error' not in columns:
        op.add_column('emails', sa.Column('delivery_error', sa.Text(), nullable=True, comment='投递失败的错误信息'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('emails')]
    if 'delivery_error' in columns:
        op.drop_column('emails', 'delivery_error')
    if 'delivery_status' in columns:
        op.drop_column('emails', 'delivery_status')
    # ### end Alembic commands ###
